## Pandas
1. it is the module/library/package of the python<br>
2. it will do data manupulation<br>
3. data collection<br>
4. data cleaning<br>
5. data analysis<br>
6.

### Data collection:-
1. csv
2. excel
3. sql

In [1]:
import pandas as pd

In [2]:
print(dir(pd))

['ArrowDtype', 'BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt8Dtype', '__all__', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_built_with_meson', '_config', '_is_numpy_dev', '_libs', '_pandas_datetime_CAPI', '_pandas_parser_CAPI', '_testing', '_typing', '_version_meson', 'annotations', 'api', 'array', 'arrays', 'bdate_range', 'col', 'compat', 'concat', 'core', 'crosstab', 'cut', 'date_range', 'describe_option', 'errors', 'eval', 'factorize', 'from_dummies', 'get_dummies', 'get_option', 'infer_freq', 'interval_range', 'io', 'isna', 'isnull', 'json_normalize', 'lreshape', 'melt', 'merge', 'merge_asof', 'merge_ordered', 'notna', 'notnull', 'offsets', 'option_context', 'options', 'pandas', 'period_range', 'pivot', 'pivot_table', 'plotting', 'qcut', 'read_clipboard', 'read_csv', 'read_excel', 'read_feather', 'read_fwf', 'read_hdf', 'read_html', 'read_iceberg', 'read_json', 'read_orc', 'read_parquet', 'read_pickle', 'read_sas', 'read_spss', 'read_sql', 'read_sql_query', 'read_sql_table', 'read_stata', 'read_table', 'read_xml', 'reset_option', 'set_eng_float_format', 'set_option', 'show_versions', 'test', 'testing', 'timedelta_range', 'to_datetime', 'to_numeric', 'to_pickle', 'to_timedelta', 'tseries', 'unique', 'util', 'wide_to_long']

In [3]:
import pandas as pd

df = pd.read_excel(r"D:\TCA_DataScience\Book1.csv.xlsx")
print(df)

     Empolyee Department   Salary  Branch
0       Pooja         it   4000.0     NaN
1   dhurendar      sales   4999.0     NaN
2        aman         Hr   5998.0     NaN
3        rajt         it   6997.0     NaN
4        rina      sales   7996.0     NaN
5     pragati         hr   8995.0     NaN
6   shivanshu         it   9994.0     NaN
7    himanshu         it  10993.0     NaN
8       sujal      sales  11992.0     NaN
9      shivam         hr  12991.0     NaN
10      rihan       slae  13990.0     NaN
11      kiran         it  14989.0     NaN
12   himanshi         it  15988.0     NaN
13      lalti         it      NaN     NaN

In [4]:
# creating own data frame
student=pd.DataFrame({'Name': ['Raj', 'Raman', 'Rohit','Ram','Pragya'], 
              'English': [19, 80, 70,97,56], 
              'Hindi': [20, 30, 25, 40, 35],
              'Maths': [30, 40, 50, 60, 70]})
student

     Name  English  Hindi  Maths
0     Raj       19     20     30
1   Raman       80     30     40
2   Rohit       70     25     50
3     Ram       97     40     60
4  Pragya       56     35     70

In [5]:
student['Total']=student['English']+student['Hindi']+student['Maths'] # ye new column create karega jisme total marks honge
student

     Name  English  Hindi  Maths  Total
0     Raj       19     20     30     69
1   Raman       80     30     40    150
2   Rohit       70     25     50    145
3     Ram       97     40     60    197
4  Pragya       56     35     70    161

In [6]:
student['Percentage']=student['Total']/3
student

     Name  English  Hindi  Maths  Total  Percentage
0     Raj       19     20     30     69   23.000000
1   Raman       80     30     40    150   50.000000
2   Rohit       70     25     50    145   48.333333
3     Ram       97     40     60    197   65.666667
4  Pragya       56     35     70    161   53.666667

In [ ]:
df.shape # kitne row or columans

(14, 4)

In [ ]:
df.info() # ato z

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Empolyee    14 non-null     str
 1   Department  14 non-null     str
 2   Salary      13 non-null     float64
 3   Branch      0 non-null      float64
dtypes: float64(2), str(2)
memory usage: 580.0 bytes

In [ ]:
df.describe() # ye numerical data ke liye use karte h

             Salary  Branch
count     13.000000     0.0
mean    9994.000000     NaN
std     3890.546041     NaN
min     4000.000000     NaN
25%     6997.000000     NaN
50%     9994.000000     NaN
75%    12991.000000     NaN
max    15988.000000     NaN

In [10]:
#find top first 5 records
df.head()

    Empolyee Department  Salary  Branch
0      Pooja         it  4000.0     NaN
1  dhurendar      sales  4999.0     NaN
2       aman         Hr  5998.0     NaN
3       rajt         it  6997.0     NaN
4       rina      sales  7996.0     NaN

In [11]:
# see last 5 records
df.tail()

    Empolyee Department   Salary  Branch
9     shivam         hr  12991.0     NaN
10     rihan       slae  13990.0     NaN
11     kiran         it  14989.0     NaN
12  himanshi         it  15988.0     NaN
13     lalti         it      NaN     NaN

In [12]:
# see 3 record only
df.head(3)

    Empolyee Department  Salary  Branch
0      Pooja         it  4000.0     NaN
1  dhurendar      sales  4999.0     NaN
2       aman         Hr  5998.0     NaN

In [14]:
df.iloc[10:16]# indexing value detah h bichz ke record show karta h

    Empolyee Department   Salary  Branch
10     rihan       slae  13990.0     NaN
11     kiran         it  14989.0     NaN
12  himanshi         it  15988.0     NaN
13     lalti         it      NaN     NaN

In [ ]:
# hamari salary  13300 is
df['Salary']>=14000#is condition ke base pe muje data chahiye

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12     True
13    False
Name: Salary, dtype: bool

In [ ]:
df[df['Salary']>=14000] #kuch nahi data ke aage df laga do to records ke saath show ho jaye ga menas ye 2d karni h

    Empolyee Department   Salary  Branch
11     kiran         it  14989.0     NaN
12  himanshi         it  15988.0     NaN